# General Champaign settings.
secret_key_base: AIzaSyDP0JurlX70eK4lvRFPSElHZ_KCCKS4JQw
omniauth_client_secret: X7jaYNN8isUvAXbrRwatzCw_
omniauth_client_id: 443756196572-28963hdq13e86canos6e3cmf2c6k630s.apps.googleusercontent.com
liquid_templating_source: db
oauth_domain_whitelist:
  - 'colorofchange.org'

aws_region: 'us-west-2'
aws_account_id: '814765110037' # set in development.local
sqs_queue_url: 'https://sqs.us-west-2.amazonaws.com/814765110037/champaign-queue'
s3_host_name: 'coc-champaign.s3-website-us-west-2.amazonaws.com'
ak_processor_url: 'url of your worker that subscribes to your SQS and ships messages to AK'
action_kit:
  akid_secret: secret-sauce

# Direct ActionKit Connection variables.
ak_api_url: 'https://act.colorofchange.org/rest/v1/'
ak_username: 'archana.ahlawat'
ak_password: 'orNU0bjMf6yj'
default_currency: 'USD'

# Assets config
s3_asset_bucket: your-asset-bucket
rails_serve_static_assets: true
compile_static: true
asset_host: 'localhost:3000'
webpack_host: 'localhost'

# NewRelic Connection information.
newrelic_license_key: 'fake-newrelic-agent'

# Social media connection information.
share_progress_api_key: share progress api key

# Braintree
braintree:
  merchant_id: braintree merchant ID
  public_key: braintree public key
  private_key: braintree private key

  # use the sandbox environment
  environment: sandbox

  merchants:
    EUR: 'braintree merchant for EUR' # for irish account. 'SumOfUs_EUR' for USA
    GBP: 'braintree merchant for GBP' # for irish account. 'SumOfUs_GBP' for USA
    USD: 'braintree merchant for USD'
    AUD: 'braintree merchant for AUD'
    CAD: 'braintree merchant for CAD'
    NZD: 'braintree merchant for NZD'
    CHF: 'braintree merchant for CHF'

  subscription_plans:
    EUR: 'EUR subscription plan id'
    GBP: 'GBP subscription plan id'
    USD: 'USD subscription plan id'
    AUD: 'AUD subscription plan id'
    CAD: 'CAD subscription plan id'
    NZD: 'NZD subscription plan id'
    CHF: 'CHF subscription plan id'

# GoCardless
gocardless:
  token: 'your gocardless sandbox token'
  environment: 'sandbox'
  gbp_charge_day: the date of month you want your gbp transactions

redis:
  host:
  port:

cache:
  host:
  port:

geocoder:
  host: 'no host'

robots: 'staging'

instantiate_stdout_logger: true

# Defines domain for page URLs
host: 'http://localhost:3000'

home_page_url: '/users/sign_in'
default_mailer_address: 'info@example.org'
smtp:
  user_name: 'smtp username'
  password: 'smtp password'

members:
  dashboard_url: 'http://example.com'

admins: ''

mixpanel_token: ''

facebook:
  pixel_id: ''

twilio:
  account_sid: ''
  auth_token: ''

development_database: 'champaign'

member_services_secret: 'hotpotato!'
oxr_app_id: '34489a6280f545c4a55ffcaa63c77b98' # get app id from https://openexchangerates.org

mailer_topic_arn:
api_key: ''

recaptcha3:
  site_key: ''
  secret_key: ''
  min_score: 0.5

recaptcha2:
  site_key: ''
  secret_key: ''

end_of_year: true
eoy_cache_timer: <%= ENV['END_OF_YEAR_CACHE_TIMER'] || 1 %>

linkedin:
  partner_id:

bulk_email_checker:
  end_point: https://api-v4.bulkemailchecker.com/
  key: